export const initialProducts = [
  {
    id: '1',
    name: 'Alfajores Artesanales',
    description: 'Deliciosos alfajores rellenos de dulce de leche, banados en chocolate o azucar impalpable.',
    category: 'Alfajores',
    variants: [
      { name: 'Tamano', options: ['Chico', 'Mediano', 'Grande'] },
      { name: 'Cobertura', options: ['Chocolate', 'Azucar'] },
    ],
    bolsitasXUd: ['1', '6', '12'],
    price: 1800,
    salePrice: 1500,
    priceNote: '',
    minQuantity: 1,
    active: true,
    emoji: '🍫',
  },
  {
    id: '2',
    name: 'Torta de Cumpleanos',
    description: 'Torta personalizada para tu celebracion especial, disponible en distintos sabores y decoraciones.',
    category: 'Tortas',
    variants: [
      { name: 'Tamano', options: ['6 porciones', '10 porciones', '15 porciones'] },
      { name: 'Sabor', options: ['Vainilla', 'Chocolate', 'Lemon pie'] },
    ],
    bolsitasXUd: [],
    price: 24500,
    salePrice: null,
    priceNote: '',
    minQuantity: 1,
    active: true,
    emoji: '🎂',
  },
  {
    id: '3',
    name: 'Cupcakes',
    description: 'Esponjosos cupcakes con frosting de colores, perfectos para cualquier ocasion.',
    category: 'Cupcakes',
    variants: [
      { name: 'Sabor', options: ['Vainilla', 'Chocolate', 'Red Velvet'] },
    ],
    bolsitasXUd: ['1', '6', '12'],
    price: 2200,
    salePrice: 1900,
    priceNote: '',
    minQuantity: 1,
    active: true,
    emoji: '🧁',
  },
  {
    id: '4',
    name: 'Brownies',
    description: 'Brownies humedos y chocolatosos. Disponibles en plancha completa o en porciones de 5 cm aprox.',
    category: 'Brownies',
    variants: [
      { name: 'Presentacion', options: ['Plancha completa', 'Porcion 5cm aprox'] },
    ],
    bolsitasXUd: [],
    price: 2600,
    salePrice: null,
    priceNote: 'Porciones: x4 $2.600 · Minimo de compra 4 u.',
    minQuantity: 4,
    active: true,
    emoji: '🍫',
  },
]

export const initialIngredients = [
  { id: '1', name: 'Harina 000', inStock: true },
  { id: '2', name: 'Azucar', inStock: true },
  { id: '3', name: 'Manteca', inStock: true },
  { id: '4', name: 'Huevos', inStock: true },
  { id: '5', name: 'Dulce de leche', inStock: false },
  { id: '6', name: 'Chocolate cobertura', inStock: true },
  { id: '7', name: 'Esencia de vainilla', inStock: true },
  { id: '8', name: 'Cacao en polvo', inStock: false },
  { id: '9', name: 'Crema de leche', inStock: true },
  { id: '10', name: 'Queso crema', inStock: true },
]

export const initialOrders = []

export const initialConfig = {
  whatsappNumber: '5491100000000',
  businessName: 'Cane Pasteleria',
  tagline: 'Dulces hechos con amor',
  description: 'Somos un emprendimiento familiar de reposteria artesanal. Cada producto esta hecho con ingredientes seleccionados y mucho amor. Pedi el tuyo!',
  instagramHandle: '@canepasteleria',
  instagramUrl: 'https://instagram.com/canepasteleria',
  facebookUrl: '',
  sinTagline: 'Sin TACC',
  logoUrl: '/logo.jpeg',
  footerNote: 'Hecho con amor',
  socialLinks: [],
  orderMessageTexts: {
    greeting: 'Hola! Quiero hacer un pedido.',
    productLabel: 'Producto',
    optionsLabel: 'Opciones',
    quantityLabel: 'Cantidad',
    closing: 'Me confirmas disponibilidad y precio final? Gracias!',
  },
}
